pool:
  vmImage: 'vs2017-win2016'

strategy:
  matrix:
    py35:
      python.version: '3.5'
    py36:
      python.version: '3.6'
    py37:
      python.version: '3.7'
    py38:
      python.version: '3.8'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    python -m pip install setuptools wheel
  displayName: 'Install common deps'

- script: |
    echo "hello"
  displayName: 'Testing'
